= README
:toc:
:sectnums:

== Introduction
Modern SQL shells like `mssql-cli`, `mycli`, `SQLcl` or `pgcli` are very convenient: they offer auto-completion, syntax highlighting, query history, a multi-line editor, and much more.

`SQL Shell` makes using your favorite SQL client even more convenient: it brings a standard interface to enter the necessary information to access your database so you don't have to remember command line options and syntax. Timesaving defaults are used for host name, port, and user.

Additional features:
* use DSNs (pre-defined connection strings) for connections
* automatic tunneling if your database is not accessible from the outside (behind a firewall or listening only on localhost interface)

== Requirements
* Python3
* Python modules
** `click`
** `sshtunnel`
** `windows-curses` (on Windows)
* SQL shells you want to use
** MSSQL: https://github.com/dbcli/mssql-cli[mssql-cli] (or legacy https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility[sqlcmd])
** MySQL: https://www.mycli.net[mycli] (or legacy https://dev.mysql.com/doc/refman/8.0/en/mysql.html[mysql])
** Oracle: https://www.oracle.com/database/technologies/appdev/sqlcl.html[SQLcl] (or legacy https://docs.oracle.com/en/database/oracle/oracle-database/21/sqpug/toc.htm[SQLPlus])
** PostgreSQL: https://www.pgcli.com[pgcli] (or legacy https://www.postgresql.org/docs/current/app-psql.html[psql])
** SQLite: https://litecli.com[litecli] (or legacy https://sqlite.org/cli.html[sqlite3])

== Installation
Copy `sql shell.py`, `sql shell.ini`, `tunnel.py`, and `tunnel.ini` to a directory of your choice.

== Usage
